[tool.poetry]
name = "repl_python3_Why-Bot"
version = "0.1.0"
description = ""
authors = ["FusionSid <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
praw = "^7.4.0"
discord = "^1.7.3"
google-api-python-client = "^2.28.0"
gTTS = "^2.2.3"
mutagen = "^1.45.1"
youtube_dl = "^2021.6.6"
cryptography = "^35.0.0"
Flask = "^2.0.2"
qrcode = "^7.3.1"
discord-py-slash-command = "^3.0.1"
google-search = "^1.1.1"
googlesearch-python = "^1.0.1"
youtube-search-python = "^1.4.9"
PyNaCl = "^1.4.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
