[tool.poetry]
name = "repl_python3_Why-Bot"
version = "0.1.0"
description = ""
authors = ["FusionSid <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^2.0.2"
aiofiles = "^0.7.0"
google-api-python-client = "^2.26.1"
cryptography = "^35.0.0"
qrcode = "^7.3.1"
google = "^3.0.0"
config = "^0.5.1"
youtube_dl = "^2021.6.6"
youtube-search-python = "^1.4.9"
PyNaCl = "^1.4.0"
py-cord = "^1.7.3"
discord = "^1.7.3"
praw = "^7.4.0"
gTTS = "^2.2.3"
pyttsx3 = "^2.90"
dblpy = "^0.4.0"
utils = "^1.0.1"
mutagen = "^1.45.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
